//
// AbsentstateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class AbsentstateResponse: Codable {

    public var date: Date?
    public var type: String?
    public var _class: String?

    public init() {}

}
