//
// AttitudeStatusResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class AttitudeStatusResponse: Codable {

    public var status: [Attitude]?
    public var count: AttitudeStatusResponseCount?

    public init() {}

}
