//
// Attitude.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Attitude: Codable {

    public var date: Date?
    public var item: String?
    public var text: String?

    public init() {}

}
