//
// AttitudeStatusResponseCount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class AttitudeStatusResponseCount: Codable {

    public var smallcite: Double?
    public var smallfault: Double?
    public var middlecite: Double?
    public var middlefault: Double?
    public var bigcite: Double?
    public var bigfault: Double?

    public init() {}

}
