//
// CalenderResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CalenderResponse: Codable {

    public var date: Date?
    public var content: String?

    public init() {}

}
