//
// Info.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Info: Codable {

    public enum Group: String, Codable { 
        case student = "student"
        case graduated = "graduated"
        case night = "night"
    }
    public var name: String?
    public var nick: String?
    public var _class: String?
    /** 用戶組別 */
    public var group: Group?

    public init() {}

}
