//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse200: Codable {

    public var week1: [TimeTableResponse]?
    public var week2: [TimeTableResponse]?
    public var week3: [TimeTableResponse]?
    public var week4: [TimeTableResponse]?
    public var week5: [TimeTableResponse]?

    public init() {}

}
