//
// Login.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Login: Codable {

    public var account: String?
    public var password: String?

    public init() {}

}
