//
// Nick.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Nick: Codable {

    public var nick: String?

    public init() {}

}
