//
// QandAResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class QandAResponse: Codable {

    public var question: String?
    public var answear: String?

    public init() {}

}
