//
// Register.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Register: Codable {

    public enum UserGroup: String, Codable { 
        case student = "student"
        case graduated = "graduated"
        case night = "night"
    }
    public var email: String?
    public var password: String?
    public var userGroup: UserGroup?
    public var schoolAccount: String?
    public var schoolPwd: String?
    public var nick: String?
    public var name: String?

    public init() {}

}
