//
// SchoolAccountPwd.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SchoolAccountPwd: Codable {

    public var schoolAccount: String?
    public var schoolPwd: String?

    public init() {}

}
