//
// SectionalExamResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SectionalExamResponse: Codable {

    public var subject: String?
    public var firstSection: Double?
    public var secondSection: Double?
    public var lastSection: Double?
    public var performance: Double?
    public var average: Double?

    public init() {}

}
