//
// StatusResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class StatusResponse: Codable {

    public var success: String?

    public init() {}

}
