//
// TimeTableResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class TimeTableResponse: Codable {

    public var start: String?
    public var end: String?
    public var subject: String?
    public var teacher: String?

    public init() {}

}
