//
// UpdateInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class UpdateInfo: Codable {

    public var password: String?
    public var newSchoolPwd: String?
    public var newNick: String?
    public var newPassword: String?
    public var newEmail: String?

    public init() {}

}
